version: '3'

services:
  server:
    container_name: TOTVS_BACKEND_SERVER
    build: '.'
    volumes: 
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'
  
  db:
    image: 'mongo'
    container_name: TOTVS_MONGODB_DEV
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db